##Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [124]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [125]:
df=pd.read_csv('Patient_Data.csv')

In [126]:
df.shape

(6, 7)

In [127]:
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [129]:
df_org=df.columns
df_org

Index(['PatientID', 'Name', 'Department', 'Doctor', 'BillAmount',
       'ReceptionistID', 'CheckInTime'],
      dtype='object')

In [130]:
df1=df.get(['PatientID', 'Department', 'Doctor', 'BillAmount'])
df1

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [131]:
df_new=df_org.drop(['ReceptionistID','CheckInTime'])
df_new

Index(['PatientID', 'Name', 'Department', 'Doctor', 'BillAmount'], dtype='object')

In [132]:
### groupby function
df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [133]:
df[df.duplicated()]

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [134]:
df.drop_duplicates(inplace=True,ignore_index=True)

In [135]:
df.duplicated().sum()

np.int64(0)

In [136]:
df.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [137]:
### filling missing values with mean
df.fillna(df['BillAmount'].mean())

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45

In [138]:
df2=pd.read_csv('Billing_Data.csv')
df2

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [139]:
df_merged=pd.merge(df,df2,on='PatientID')
df_merged

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,1000,4000

In [140]:
### create a new dataframe in excel sheet as df3 and uploading it in the python environment
df3=pd.read_csv('New_Patient.csv')
df3

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,106.0,Sofia,Dermatology,Dr.Aziz,6000.0,3.0,13-01-2023 10:30,1000.0,5000.0
1,107.0,Rahul,Cardiology,Dr.Allen,4000.0,1.0,14-01-2023 11:44,1200.0,2800.0
2,108.0,Ajay,Ophthalmology,Dr. Izhaan,5000.0,2.0,15-01-2023 11:00,900.0,4100.0
3,109.0,Sumit,Nephrology,Dr. Zillaid,7000.0,1.0,13-01-2023 12:00,1400.0,5600.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
concat_df=pd.concat([df,df3])
concat_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101.0,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,NaN,NaN
1,102.0,Bob,Neurology,Dr. John,NaN,2.0,2023-01-11 10:30,NaN,NaN
2,103.0,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00,NaN,NaN
3,104.0,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00,NaN,NaN
4,105.0,Eva,Dermatology,Dr. Rose,NaN,2.0,2023-01-14 08:45,NaN,NaN
0,106.0,Sofia,Dermatology,Dr.Aziz,6000.0,3.0,13-01-2023 10:30,1000.0,5000.0
1,107.0,Rahul,Cardiology,Dr.Allen,4000.0,1.0,14-01-2023 11:44,1200.0,2800.0
2,108.0,Ajay,Ophthalmology,Dr. Izhaan,5000.0,2.0,15-01-2023 11:00,900.0,4100.0
3,109.0,Sumit,Nephrology,Dr. Zillaid,7000.0,1.0,13-01-2023 12:00,1400.0,5600.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
### new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [143]:
df_data=pd.read_csv('new_data.csv')
df_data

   InsuranceCovered  FinalAmount
0              1000         5000
1              1200         2800
2               900         4100
3              1400         5600

In [147]:
conca_data=pd.concat([df,df_data],axis=1)
conca_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,1000.0,5000.0
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1200.0,2800.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,900.0,4100.0
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,1400.0,5600.0
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,NaN,NaN